name: pre_merge
on:
  workflow_dispatch:
    inputs:
      pr:
        description: Pull request number
        type: string
        required: true
      sha:
        description: Head sha of the PR
        type: string
        required: true
      ref:
        description: Target branch
        type: string
        required: true
      repo:
        description: Target repository
        type: string
        required: true

jobs:
  init-status:
    runs-on: ubuntu-latest
    steps:
      - name: Initial workflow status
        uses: qualcomm-linux/kernel-config/.github/actions/workflow_status@main
        with:
          sha: ${{ inputs.sha }}
          action_mode: start
          check_name: pre-merge
          repo: ${{ inputs.repo }}
          GH_TOKEN: ${{ secrets.PAT }}

  loading:
    needs: [init-status]
    uses: qualcomm-linux/kernel-config/.github/workflows/loading.yml@main
    secrets: inherit

  build:
    needs: [loading, init-status]
    uses: qualcomm-linux/kernel-config/.github/workflows/build.yml@main
    secrets: inherit
    with:
      docker_image: kmake-image:ver.1.0
      build_matrix: ${{ needs.loading.outputs.build_matrix }}
      pr_number: ${{ inputs.pr }}
      branch: ${{ inputs.ref }}
      bootbins: ${{ needs.loading.outputs.bootbins }}

  check_run:
    runs-on: ubuntu-latest
    needs: [init-status, loading, build]
    steps:
      - name: Post check run
        uses: qualcomm-linux-stg/kernel-config-test/.github/actions/check_run@main
        with:
          sha: ${{ inputs.sha }}
          repo: ${{ inputs.repo }}
          s3_location: ${{ needs.build.outputs.s3_location }}
          APPID: ${{ secrets.APPID }}
          PVK: ${{ secrets.PVK }}

  test:
    needs: [init-status, loading, build]
    uses: qualcomm-linux/kernel-config/.github/workflows/test.yml@main
    secrets: inherit
    with:
      docker_image: kmake-image:ver.1.0
      build_matrix: ${{ needs.loading.outputs.build_matrix }}
      full_matrix: ${{ needs.loading.outputs.full_matrix }}

  final-status:
    runs-on: ubuntu-latest
    needs: [init-status, loading, build, test]
    if: always()
    steps:
      - name: Final workflow status
        uses: qualcomm-linux/kernel-config/.github/actions/workflow_status@main
        with:
          sha: ${{ inputs.sha }}
          action_mode: ${{ needs.test.result }}
          check_name: pre-merge
          repo: ${{ inputs.repo }}
          GH_TOKEN: ${{ secrets.PAT }}
