name: pre_merge
on:
  workflow_dispatch:
    inputs:
      pr:
        description: Pull request number
        type: string
        required: true
      sha:
        description: Head sha of the PR
        type: string
        required: true
      ref:
        description: Target branch
        type: string
        required: true
      repo:
        description: Target repository
        type: string
        required: true

jobs:
  init-status:
    runs-on: ubuntu-latest
    steps:
      - name: Initial workflow status
        uses: qualcomm-linux/kernel-config/.github/actions/workflow_status@main
        with:
          sha: ${{ inputs.sha }}
          action_mode: start
          check_name: pre-merge
          repo: ${{ inputs.repo }}
          GH_TOKEN: ${{ secrets.PAT }}

  loading:
    needs: [init-status]
    uses: qualcomm-linux/kernel-config/.github/workflows/loading.yml@main
    secrets: inherit

  build:
    needs: [loading, init-status]
    uses: qualcomm-linux/kernel-config/.github/workflows/build.yml@main
    secrets: inherit
    with:
      docker_image: kmake-image:ver.1.0
      build_matrix: ${{ needs.loading.outputs.build_matrix }}
      pr_number: ${{ inputs.pr }}
      branch: ${{ inputs.ref }}
      bootbins: ${{ needs.loading.outputs.bootbins }}
      repo: ${{ inputs.repo }}

  check_run:
    if: inputs.repo == 'qualcomm-linux/kernel'
    runs-on: ubuntu-latest
    needs: [init-status, loading, build]
    steps:
      - name: Post check run
        uses: qualcomm-linux/kernel-config/.github/actions/check_run@main
        with:
          sha: ${{ inputs.sha }}
          repo: ${{ inputs.repo }}
          s3_location: ${{ needs.build.outputs.s3_location }}
          APPID: ${{ secrets.APPID }}
          PVK: ${{ secrets.PVK }}

  test:
    if: inputs.repo == 'qualcomm-linux/kernel'
    needs: [init-status, loading, build]
    uses: qualcomm-linux/kernel-config/.github/workflows/test.yml@main
    secrets: inherit
    with:
      docker_image: kmake-image:ver.1.0
      build_matrix: ${{ needs.loading.outputs.build_matrix }}
      full_matrix: ${{ needs.loading.outputs.full_matrix }}
      kernel_version: ${{ needs.build.outputs.kernel_version }}
      commit_SHA: ${{ inputs.sha }}

  comment:
    needs: [test]
    uses: qualcomm-linux/kernel-config/.github/workflows/comment.yml@main
    if: always() && needs.test.result != 'skipped' 
    secrets: inherit
    with:
      pr_number: ${{ inputs.pr }}
      sha: ${{ inputs.sha }}
      repo: ${{ inputs.repo }}

  final-status:
    runs-on: ubuntu-latest
    needs: [init-status, loading, build, test, comment]
    if: always()
    steps:
      - name: Final workflow status
        uses: qualcomm-linux/kernel-config/.github/actions/workflow_status@main
        with:
          sha: ${{ inputs.sha }}
          action_mode: ${{ needs.test.result != 'skipped' && needs.test.result || needs.build.result }}
          check_name: pre-merge
          repo: ${{ inputs.repo }}
          GH_TOKEN: ${{ secrets.PAT }}
